### PR TITLE
std::iota error fixed

### PR DESCRIPTION
**Pull request by michaelpantic**
Issue:
Did not compile on gcc 7.3.0 (default on ubuntu 18.04). Error: 'iota’ is not a member of ‘std’. C++11 was activated, so that wasn't the issue.

Reason:
std::iota has been introduced into the standard lately and may be in different headers for different compilers, even if they're c++11 compliant. Hopefully that fixes it.

@helenol  ptal and check if it still compiles on your machine ;-)

### CODE REVIEW

**Comment by michaelpantic** [comment]
@helenol  btw since mav_trajectory_generation is not a submodule of mav_pathplanning anymore it doesn't get included according to our standard installation manual - and things fail to build. I'll add id to the rosinstalls.

**Comment by michaelpantic** [comment]
See https://github.com/ethz-asl/mav_tools/pull/379
